name: JavaScript CI with npm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 16.13
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1

      - name: Install dependencies
        run: npm ci

      - name: Debug Node.js Environment
        run: |
          node -v
          npm -v
          npm ls async_hooks

      - name: Run tests
        run: npm run test:unit

      - name: Build
          run: npm run build
